### ISSUE TITLE
Godot 4.2.2 support?

### ISSUE THREAD

**Issue by TrevorBlythe** [decacis/godot_oculus_platform#6]
### Feature description

4.2.2 is giving way more fps and stability in VR then 4.2. But when I try to run this code snippet:
```gdscript
	GDOculusPlatform.initialize_android_async("314159265358979").then(func(_initialization_resp):
		print("Oculus Platform initialized!")
	).error(func(initialization_err):
		print("Oculus Platform initialization error: ", initialization_err)
	)
```
It says, Cannot call method 'then' on a null value. I also tried it with my own app ID.

**Comment by decacis** [comment]
Hi, I just tested in 4.2.2-stable and was able to initialize correctly.

Did you enable the plugin in Project Settings -> Plugins -> Godot Oculus Platform ?

**Comment by TrevorBlythe** [comment]
Im on 4.2.2 stable also. Im also on ubuntu. I did enable it but it didnt work, so I cloned it again and followed the build steps, it built successfully and I import the demo godot project and it has an error "Parser Error: Identifier "GDOculusPlatform" not declared in the current scope." :(((

**Comment by decacis** [comment]
That is weird... I would recommend sticking with the files from the latest release, since they at least are recognized inside the editor.

Keep in mind that this plugin only works on android, when deploying the game to the headset. When you run from Windows/Linux/MacOS you **should** get an error saying "Godot Oculus Platform only works with the Meta Quest (android).", thought from looking at the code, it seems like I missed a part of the code and that's why you get the "Cannot call method 'then' on a null value" message.

**Comment by TrevorBlythe** [comment]
Okay that makes sense I was just running it on my computer to test if it worked or not
